version: "3.5"
name: "bdi"

volumes:
  pg_data: {}

services:
  bdi:
    image: bdi
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:15

    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
        - "5433:5432"


  